### ISSUE TITLE
missing requirements.txt file; fails to start

### ISSUE THREAD

**Issue by abartov** [dpriskorn/LexUtils#56]
The instructions mention a requirements.txt file, but no such file exists in this repo.

Trying the run the code yields:

``` bash
python lexutils.py 
Traceback (most recent call last):
  File "/home/asaf/dev/LexUtils/lexutils.py", line 3, in <module>
    from lexutils import main
  File "/home/asaf/dev/LexUtils/lexutils/main.py", line 6, in <module>
    from lexutils.config import config
ImportError: cannot import name 'config' from 'lexutils.config' (/home/asaf/dev/LexUtils/lexutils/config/__init__.py)
```

**Comment by abartov** [comment]
It fails to start complaining about a missing ModuleNotFoundError: No module named 'riksdagenapi'
(that module probably shouldn't be mandatory, for people who may want to use the tool only in other languages.)

**Comment by abartov** [comment]
after manually installing riksdagenapi using pip (in a virtualenv), it still fails to start:

``` bash
$ ~/venv/bin/python lexutils.py 
Traceback (most recent call last):
  File "/home/asaf/dev/LexUtils/lexutils.py", line 3, in <module>
    from lexutils import main
  File "/home/asaf/dev/LexUtils/lexutils/main.py", line 7, in <module>
    from lexutils.modules import usage_examples_module
  File "/home/asaf/dev/LexUtils/lexutils/modules/usage_examples_module.py", line 10, in <module>
    from riksdagenapi.riksdagen import Riksdagen
ModuleNotFoundError: No module named 'riksdagenapi.riksdagen'
```

**Comment by dpriskorn** [comment]
This tool is no longer in development and I'm not keen on changing that so I'm going to archive it instead.

Poetry is now used to handle the dependecies.
Try 
pip install poetry && poetry install

**Comment by abartov** [comment]
Thank you for this response. Is there another tool that superseded this?

**Comment by dpriskorn** [comment]
I don't know. What are your needs?

**Comment by abartov** [comment]
Pretty much what your tool seems to have done -- adding usage examples from textual sources. I was sufficiently motivated to build a tool myself. It is Web-based and relies on Wikisource. You can find it [here](https://luthor.toolforge.org).
